[build]
cmd = "go build -o /tmp/bin/api ./cmd/api"
bin = "/tmp/bin/api"

[watch]
include_ext = ["go", tpl", tmpl", html", css", scss", js", ts", sql", jpeg", jpg", gif", png", bmp", svg", "webp", "ico"]
exclude_dir = [""]
