[build]
cmd = "go build -o /tmp/bin/api ./cmd/api"
bin = "/tmp/bin/api"
kill_delay = 3000

[watch]
include_ext = ["go", "tpl", "tmpl", "html", "css", "scss", "js", "ts", "sql", "jpeg", "jpg", "gif", "png", "bmp", "svg", "webp", "ico"]
exclude_dir = ["vendor", ".git"]

# Debounce file change events by 1000ms (1 second)
delay = 1000
